Mis Pato Cambios
Safe-Corp-Jiva/frontend pull request #19
Opened 2024-05-18 00:39 UTC by patolinbr

🌪️

2024-05-18 00:45 UTC, patolinbr reviewed
Good from Pato

2024-05-22 02:31 UTC, ronuma requested changes
Also, pr name and description we have no clue

2024-05-22 02:31 UTC, ronuma commented on package.json
> +    "bootstrap": "^5.3.3",
IS THIS NECESSARY?

2024-05-22 02:31 UTC, ronuma commented on src/app/(main)/@agent/wait/page.tsx
> +function wait() {
CamelCase for components

2024-05-22 02:31 UTC, ronuma commented on src/app/(main)/@agent/wait/page.tsx
> +export default wait
CamelCase

2024-05-22 23:27 UTC, IksGarG commented on src/app/(main)/@agent/wait/page.tsx
> +function wait() {
Fixed

2024-05-22 23:28 UTC, IksGarG commented on src/app/(main)/@agent/wait/page.tsx
> +export default wait
Fixed

2024-05-22 23:33 UTC, IksGarG approved these changes
Fixed changes, but need to work with @patolinbr to NOT INSTALL LIBRARIES IF NOT REQUIERD.

2024-05-22 23:34 UTC, merged